// Mock data for development
export const mockUser = {
  id: "1",
  name: "John Doe",
  email: "john.doe@example.com",
  avatar: "/placeholder.svg?height=40&width=40",
  phone: "+1 (555) 123-4567",
  address: "123 Main St, New York, NY 10001",
}

export const mockLawyer = {
  id: "1",
  name: "Sarah Johnson",
  email: "sarah.johnson@lawfirm.com",
  avatar: "/placeholder.svg?height=40&width=40",
  specialty: "Corporate Law",
  experience: 8,
  rating: 4.8,
  totalReviews: 127,
  phone: "+1 (555) 987-6543",
  barNumber: "NY123456789",
  education: "Harvard Law School, JD",
}

export const mockUserBookings = [
  {
    id: "1",
    lawyerName: "Sarah Johnson",
    lawyerSpecialty: "Corporate Law",
    date: "2024-01-15",
    time: "10:00 AM",
    status: "upcoming",
    type: "Video Call",
    duration: "30 minutes",
    fee: "$150",
  },
  {
    id: "2",
    lawyerName: "Michael Chen",
    lawyerSpecialty: "Family Law",
    date: "2024-01-10",
    time: "2:00 PM",
    status: "completed",
    type: "Phone Call",
    duration: "45 minutes",
    fee: "$120",
  },
  {
    id: "3",
    lawyerName: "Emily Rodriguez",
    lawyerSpecialty: "Criminal Defense",
    date: "2024-01-08",
    time: "11:30 AM",
    status: "completed",
    type: "In-Person",
    duration: "60 minutes",
    fee: "$200",
  },
  {
    id: "4",
    lawyerName: "David Wilson",
    lawyerSpecialty: "Real Estate Law",
    date: "2024-01-20",
    time: "3:00 PM",
    status: "upcoming",
    type: "Video Call",
    duration: "30 minutes",
    fee: "$130",
  },
]

export const mockLawyerConsultations = [
  {
    id: "1",
    clientName: "John Doe",
    clientEmail: "john.doe@example.com",
    problemDescription: "Need help with contract review for a new business partnership agreement.",
    date: "2024-01-15",
    time: "10:00 AM",
    duration: "30 minutes",
    status: "upcoming",
    type: "Video Call",
    fee: "$150",
  },
  {
    id: "2",
    clientName: "Alice Smith",
    clientEmail: "alice.smith@example.com",
    problemDescription: "Seeking advice on employment law regarding wrongful termination case.",
    date: "2024-01-16",
    time: "2:00 PM",
    duration: "45 minutes",
    status: "upcoming",
    type: "Phone Call",
    fee: "$180",
  },
  {
    id: "3",
    clientName: "Robert Brown",
    clientEmail: "robert.brown@example.com",
    problemDescription: "Corporate merger legal documentation and compliance review.",
    date: "2024-01-17",
    time: "11:00 AM",
    duration: "60 minutes",
    status: "upcoming",
    type: "In-Person",
    fee: "$250",
  },
]

export const mockLawyerStats = {
  totalBookings: 156,
  completedSessions: 142,
  totalReviews: 127,
  averageRating: 4.8,
  totalEarnings: "$23,450",
  thisMonthBookings: 12,
  thisMonthEarnings: "$1,890",
}
